apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: valden01/user:latest
          ports:
            - name: http
              containerPort: 8081
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  type: LoadBalancer
  selector:
    app: user
  ports:
    - protocol: TCP
      name: http
      port: 81
      targetPort: 8081
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081